import Head from 'next/head';

import {Grid} from '@mui/material';
import {createTheme, ThemeProvider} from '@mui/material/styles';
import Nav from '../comps/nav.js';
import Intro from '../comps/intro';
import Projects from '../comps/projects';
import Skills from '../comps/skills';
import About from '../comps/about';
import Footer from '../comps/footer.js';
const theme = createTheme({
  palette: {
    primary: {
      main: '#f7fffc',
    },
    secondary: {
      main: '#3b2d8e',
    },
  },
  typography: {
    fontFamily: ['Times New Roman', 'Arial', 'sans-serif'].join(','),
  },
});

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Grid
        container
        spacing={4}
        direction="column"
        sx={{
          backgroundColor: 'primary.main',
        }}
      >
        <Head>
          <title>Luqman Hassan | Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.png" />
        </Head>

        <Nav />
        <Intro />
        <Projects />
        <Skills />
        <About />
        <Footer />
      </Grid>
    </ThemeProvider>
  );
}
